service: reto-softek-api

frameworkVersion: '3'

plugins:
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:*
    Resource:
      - '*'

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}